### ISSUE TITLE
Cost function

### ISSUE THREAD

**Issue by RichRick1** [theochem/PyCI#29]
The task is to select Slater Determinants based on a given cost function. 
There are methods for selecting SDs based on [excitation level](https://github.com/theochem/PyCI/blob/master/pyci/excitation_ci.py) and [seniority](https://github.com/theochem/PyCI/blob/master/pyci/seniority_ci.py) are already implemented. 
Also, user is able to select SDs based on number of orbital nodes. This is also implemented with [GKCI algorithm](https://github.com/theochem/PyCI/blob/master/pyci/gkci.py) 
We need to implement selection of SD given energy of the orbitals (similar to the number of orbital nodes)
ToDo:

- [x] #33
- [x] #32
- [x] #37
      1. Create almost the same version of `odometer_one_spin` and `odometer_two_spin` functions in the  cost.py file, but changing the selection criteria by removing smoothness factor.
      2. (_Recommended_) Implement general version of `odometer_one_spin` and `odometer_two_spin` functions in utility.py file that takes selection criteria (probably in the form of another function) as input.
     
UPD:

- [ ] #36

**Comment by AlexandreDeCamargo** [comment]
Cool

**Comment by Pavlo3P** [comment]
Fascinating!

**Comment by manyasha-n-m** [comment]
comment

**Comment by manyasha-n-m** [comment]
I would like to choose the first task _(In the new file cost.py implement function add_energy. The input should be similar to the add_gkci. It should take wavefunction and energies as input.)_, assuming that the functions from the subtask 2 are already moved to utility.py
Please react for my comment if anyone has something against it (thumb down), or if you say OK (thumb up)

**Comment by alnaba1** [comment]
I'd be happy to work on the second task. I'll be familiarizing myself with the material over the next couple days in preparation before I start contributing (should have some results during weekend ideally).

**Comment by Pavlo3P** [comment]
@alnaba1 yep, let's dive in it before, and on Friday we may discuss how we'd like to distribute the tasks. I'll write you an email for more details.

**Comment by RichRick1** [comment]
@PaulWAyers what would be the analogue expression of the [selection criteria in GKCI ](https://github.com/theochem/PyCI/blob/86035ff71c2c585f6ecf388de9091dca7ecfaaf0/pyci/gkci.py#L226) for the energy?

**Comment by PaulWAyers** [comment]
You'd sum the orbital energies. 

[GKCI is based on the asymptotic convergence of CI coefficients as a function of the number of nodes of the molecular orbitals](https://www.sciencedirect.com/science/article/pii/S2210271X18304250), which is predicted to be (inversely proportional to)

$$
f(\tau,\mathbf{x}) = ||\mathbf{x}||_1 + \tau ||\mathbf{x}||_{\infty} 
$$

where the $\ell_1$ and $\ell_\infty$ norm are denoted in the obvious way and $-1 \le \tau \le \infty$. 

In the energy case, the only sensible criterion is only the $\tau=0$ case, so one merely uses 

$$
f(\mathbf{\epsilon}) = \sum_{p \in \text{occupied orbitals}} \epsilon_p
$$

The $\ell_1$ norm is a bad idea here because the orbital energies generally have both negative and positive values and because shifting the orbital energies by a constant is not very useful.

Evidently, according to @msricher there are some other forms of cost function beyond GKCI that haven't been used but which are implemented. I'm not sure; they are not documented where I have seen them. I think the method he is referring to (if I recall correctly) is method #3 in the attached notes.

[GKCInotes5.pdf](https://github.com/theochem/PyCI/files/14791861/GKCInotes5.pdf)

**Comment by manyasha-n-m** [comment]
Hello all, I did the part with add_energy, however I need to know what are the changes in the odometer_one_spin and odometer_two_spin, so that I delete them from my file and simply "import yours". Can we discuss it during the call today?
Thank you in advance!

**Comment by msricher** [comment]
@PaulWAyers There's both method 2 and 3 from your notes, called "gamma" and "interval" respectively in the code. I haven't tested them much.

**Comment by RichRick1** [comment]
@msricher do we have tests for add_gkci algorithm or odometer algorithms?

**Comment by RichRick1** [comment]
@PaulWAyers what should be the expression for calculating maximum value of the energy that is allowed. It should be an analog of `q_max` parameter [here ](https://github.com/theochem/PyCI/blob/86035ff71c2c585f6ecf388de9091dca7ecfaaf0/pyci/gkci.py#L223)
Logic for the rest of the code seems to be the same

**Comment by PaulWAyers** [comment]
It's a user parameter. Usually the calculation would be run for several different threshholds and then extrapolated. I'm not sure what the default value should be, but perhaps no default at all is sensible at least for starters.
